### ISSUE TITLE
gun.map().on(cb) magically stopped updating?

### ISSUE THREAD

**Issue by amark** [amark/gun#101] opened 2015-10-07 19:42 UTC
Building trace game (multiplayer agario/tron), and everything was working fine and then suddenly I stopped getting updates?

This gives me reason to think I caused the problem to happen, since I've never seen this before. None-the-less reporting it so I can figure out what is going on anyways.

**Comment by amark** [comment] 2015-10-07 22:40
DEFINITELY related to #98 because when I switched away from using a path on a not-yet-defined field to having it defined first then things worked. So I bet I no longer got updates because in #98 it says the data I was updating was getting accidentally attached to the parent (I bet this is the case) which would explain why I wouldn't be getting updates.

@metasean how do I merge this into #98 and keeping #98 as the main one?

**Comment by metasean** [comment] 2015-10-07 23:01
Duplicate of #98

**Closed by metasean** 2015-10-07 23:01 UTC
Labels: fix

**Comment by amark** [comment] 2015-10-08 03:59
oh, duh. thanks.
