### ISSUE TITLE
SPARQL Querying / Indexes

### ISSUE THREAD

**Issue by jacobpdq** [amark/gun#596] opened 2018-08-07 13:32 UTC
Hey all, I'm looking to implement gundb with node-solid & would like to know if it's capable of handling indexed queries / SPARQL querying. Can anyone provide me with more information / forays?

**Comment by folkvir** [comment] 2018-08-10 15:05
Please refer to gun-level coupled with [levelgraph](https://github.com/levelgraph/levelgraph)
I think you can try to start with levelgraph to not re-invent the wheel.

**Comment by amark** [comment] 2018-08-15 20:44
@jacobpdq we currently have a [GraphQL](https://github.com/brysgo/graphql-gun) adapter, which also means SQL, SPARQL, Mango, Cypher, and other query languages are all possible of being built on top. But we do not currently have a SPARQL adapter - want to help build it (should be easier than the GraphQL one!)?

@folkvir does gun-level + levelgraph allow for SPARQL queries? I doubt it. Also, we're deprecating gun-level in favor of our new RAD (Radix storage engine) adapter, which we'll be maintaining officially moving forward, that we'll add a Level connector for.

**Comment by jacobpdq** [comment] 2018-08-16 02:02
<https://github.com/RubenVerborgh/SPARQL.js/> should help here. At the moment I'm swamped with work but this is on my radar. I'll have a look at RAD - please let me know when it's expected to be ready for development (and perhaps production).

Ideally, data should be able to be replicated across all hosting networks / adapters, but that's for another day.

**Comment by folkvir** [comment] 2018-08-16 10:27
@amark levelgraph allows to write SPARQL queries. At least in it's simplest form with Basic Graph Patterns (BGPs). But for a full SPARQL 1.0 or 1.1 support levelgraph can be a beginning.
Just for my information, do you have any documentation about RAD, I see a lot of discussions about it but nothing usefull for test it or even learn about what you are doing, is it a private work? What is the difference with the level-db adapter? (Perhaps it's not the right place to talk about it...)

@jacobpdq SPARQL.js is just a parser for SPARQL queries. Yes of courses this tool is very usefull. As you can parse the query and create a physical/virtual plan easily. I already use it in severals project but this is not enough to make a SPARQL engine with SPARQL 1.0./1.1 support. A colleague already published a project for writing SPARQL query engine. Can I suggest you to take a look of it? @Callidon [Callidon/sparql-engine](https://github.com/Callidon/sparql-engine)

Also if you want more information about Ruben Verborgh's project you can still take a look at [RDFJS](https://github.com/rdfjs) or even its Triple Pattern Fragment implementation with its server and client.
There is also [Rdfstore-js](https://github.com/antoniogarrote/rdfstore-js) and [hexastore](https://github.com/crubier/Hexastore) which is based on a research article as SPARQL query engines in the browser. You also have the new [Comunica](https://github.com/comunica/comunica) of Ruben's team.  It's an interesting project. If you want other information, I will pleased to answer it ;)

**Comment by jacobpdq** [comment] 2018-08-16 12:05
@folkvir Verborgh's colleagues also send me the graphql-ld demo [paper](https://comunica.github.io/Article-ISWC2018-Demo-GraphQlLD/). Yes, Comunica is an ideal approach.

 Either something gets built on top of the graphql layer @amark or the sparql adapter is built. Personally, I'm more familiar with apollo but don't enjoy library soup. Thoughts? I'm not well-versed in sparql but @callidon 's sparql engine should help here.

@amark also interested in RAD & saw the gif. If I understand, it's ideal for graphs / named graphs?

**Comment by jacobpdq** [comment] 2018-08-16 12:17
re: Hexastore:  the replication of these representations in a five-fold manner may exceed the available storage capacity [Hexastore:
Sextuple Indexing for Semantic Web Data Management ∗](http://www.vldb.org/pvldb/1/1453965.pdf).

But hey, if this is distributed and I want my graphs then I'll add a few hard drives or filenets...

**Comment by folkvir** [comment] 2018-08-16 13:56
@jacobpdq What do you want to do exactly? A SPARQL query engine using Gun or an engine using levelgraph? These are completely different approaches. 
Gun is a distributed and realtime graph-based engine but not **currently** well suited for SPARQL query. The realtime here is a problem, will you be able to query the database in "real-time" like rdfstore-js with its event-like API? Like for example, registering the query and updating the query every time a triple matching the triple patterns of your query is inserted? This method is, on my mind, too heavy to be accepted. Even dealing with transactions you will still have missing values which could be added during the query processing.  In this scenario you will have to deal with Streams which is not an easy subject.
If you want to use the levelgraph module which is a Triple Store using the levelDB adapter, you can deal with data locally by inserting your data in the browser and query the local dataset with an existing engine such as the Callidon's one.  
It's up to you to choose what is best for your need. ;)

**Comment by Callidon** [comment] 2018-08-16 13:56
Hi all, popping into the conversation

@jacobpdq I am close to releasing a firs version of the framework to build SPARQL query engines. We started this work with some interns, so I still need to finish up some work before releasing a clean prototype (the repo doesn't even have a proper README). Basically, all you have to do is to implements a subclass of a Graph, which handles insertion, deletion and retrieval of RDF triples from the RDF Graph. I will keep you updated when the first release will be made.
As @folkvir mentioned, I've built a basic integration with LevelGraph for testing purpose. You can check it [here](https://github.com/Callidon/sparql-engine/blob/master/tests/utils.js), if you want to get an idea.

If you need more information about SPARQL, I point you to the [Official W3C specification](https://www.w3.org/TR/sparql11-query/), which is very exhaustive. My library will support basic SPARQL querying (SELECT, ASK, CONSTRUCT and DESCRIBE), but support for the SPARQL UPDATE protocol is unfinished and will come later.

Next, about GraphQL-LD. If you want to built an integration between Solid and Gun.js, you will be working with Linked Data, so using directly RDF Graphs seems the best idea to me. It reduce the difficulty of integration (no need for a wrapper between GraphQL and RDF), and as Solid apps will read RDF triples from the server (as required by the spec), it seems more natural to me.

Finally, about Comunica. My interns first design the engine as an extension of Comunica. However, they reported that extending this engine was very difficult due to its software architecture. So, they switched to a standalone library with a design closes to [Apache Jena](https://jena.apache.org/), the reference Java framework for all RDF and SPARQL related things. It did not dive deep into Comunica arch personally, but I trust my interns enough to stick to their approach.

**Comment by amark** [comment] 2018-08-20 21:47
@jacobpdq apologies if I'm not understanding the conversation back and forth in this thread (I feel like I'm missing some other context... I believe you guys all know each other / friends and are talking about something I'm not quite aware of - which is fine, just pardon my ignorance!!!)

Yes, Internet Archive integrated GUN in 1 week, go1dfish built decentralized Reddit (notabug.io) in 1 week, lots of fun awesome things - would love to have SOLID getting P2P replicated and cryptographically secured linked data running on top of GUN + SEA! Had a 20 minute chat with TBL and Ruben about it, was a huge honor.

SPARQL is one of those things people mention occasionally, but nobody brave enough to actually build/implement - so sorry, I don't know anybody who overlaps, but asking on the https://gitter.im/amark/gun doesn't hurt. But it sounds like you guys have done the real hard work!

Since you guys have the tree builder for it, and I'm assuming there is actually a tree involved, it should be hard to traverse the SPARQL tree recursively calling `prevRef.get(newTreeBranch)` in GUN. Points where you need to do conditional logic can use our selective property loading `gun.get('users').get('bob')` (only grabs bob from users, not 2B users...) to "lookahead" into the property of conditional logic (`thisQueryTree.get('age')`) and retrieve its value (nothing else) and then you can perform full Turing-complete JS-based (I assume the AST parser can convert the conditional query into a JS function?) do then `age > 12` which if true you'd then tell gun `loadThisBranch` but if false `skipThisBranch`, etc.

Obviously work, but if you know how to do a GUN graph traversal, and you know how to walk your SPARQL tree, it should be a bunch of 1-1 logic.

Another route is (if you control all peers in your network), you can use GUN's wire spec to just payload the full SPARQL query over GUN's `GET` wire command, then peers in the network can have a SPARQL adapter that checks the `GET` is SPARQL and locally (remotely) runs the query and syncs back the graph. The downside with this approach is it requires controlling all peers in the network to make sure they have SPARQL on it. The 1st approach is better (how the GraphQL extension does it) as it allows you to do SPARQL queries even if remote peers (or peers of peers, etc.) don't know SPARQL.

What is next?

**Comment by jacobpdq** [comment] 2018-08-27 15:18
Next is creating a method of storing the nodes & edges to be retrieved by a query - which should be SPARQL but, for now, isn't necessary. @folkvir do you think gun SHOULD be well-suited to use in an environment? Maybe I'm just trying to put a hexagonal peg in a square hole. 

There needs to be a way for all of this information to resolve at any rate - whether it's in a stream, local, etc... there should be a method of ensuring the data is up-to-date, however it's distributed... and however it's linked. @amark I saw the presentation dealing with futurestores (if that's what you call them) - does it apply in this case? There's an nth degree of data required to resolve as links for nodes but should be solved very well with a p2p system.

**Comment by amark** [comment] 2018-08-27 20:30
@jacobpdq @folkvir yes, GUN's resolves all the data correctly, that is the job of the conflict-resolution algorithm in a fully P2P/decentralized environment :).

**Comment by amark** [comment] 2018-08-29 23:05
@folkvir @jacobpdq @Callidon hey all, it has been a great discussion - I've noticed @jacobpdq has moved the discussion to SOLID's gitter and GUN's gitter. Let's continue it there, and I'm gonna close this issue as it is not a bug.

**Closed by amark** 2018-08-29 23:05 UTC

**Comment by jacobpdq** [comment] 2018-08-29 23:07
Great, agreed & thx.
