### ISSUE TITLE
socket.io conflict error on header?

### ISSUE THREAD

**Issue by Lightnet** [amark/gun#282] opened 2016-11-27 07:39 UTC
I did some simple test on setup some basic server using express and socket.io with gun. I get header error some reason. I wonder if this is bug or the way it handle network error access.

**Comment by amark** [comment] 2016-11-27 09:10
As in gun can't run alongside a socket.io server? Or that when using socket.io with gun it does not work? (Currently gun has no socket.io adapters and thus will not work with it. But it isn't hard to build one.)

**Comment by Lightnet** [comment] 2016-11-27 18:55
I am just running both of them but just got an error on header that all. Reason it chat on socket.io and gun for database but depend what I building. Or Socket.io for game network design but lag but run local not site for what I am design to create game editor, server, client type of build.

**Comment by PsychoLlama** [comment] 2016-11-28 19:52
@Lightnet The WebSocket driver that comes bundled with gun is a very thin layer above `window.WebSocket`, and probably (I'm guessing here) isn't compatible with the `socket.io` protocol.

Although gun doesn't try to be compatible with socket.io out of the box (as @amark mentioned, a plugin can be built for it), it does run a socket server and might be causing issues when used with socket.io.

Do you have a stack trace you could post here, or maybe some code to reproduce the error?

**Comment by Lightnet** [comment] 2016-11-28 22:00
Well it ok I guess. I did simple setup. Express, socket.io and gun. Bare minimal code for server side and client. As well the current latest ones.(stable release)

`socket.io.js:6605 WebSocket connection to 'ws://127.0.0.1/socket.io/?EIO=3&transport=websocket&sid=r1jSm_QMD5zc20z_AAAA' failed: Invalid frame header`

**Comment by PsychoLlama** [comment] 2016-11-29 02:37
I was able to reproduce the bug... looks like running the two WebSocket servers attached to the same server (`socket.io` and `gun`) will cause an issue.

I'm investigating to see if gun is the `Invalid frame header` culprit. Meanwhile, this is the code I'm testing with:

**`server.js`**
```js
var server = require('http').Server();
var Gun = require('gun');
require('socket.io')(server);

var gun = Gun();

gun.wsp(server);

server.listen(8080);
```

**`index.html`**
```html
<!DOCTYPE html>
<html lang='en'>
<head>
  <meta charset='UTF-8'>
  <title>Socket.io/Gun clash</title>
</head>
<body>
	<script src='http://localhost:8080/socket.io/socket.io.js'></script>
	<script>
		const socket = io('http://localhost:8080');
	</script>
</body>
</html>
```

Logs:

```
WebSocket connection to 'ws://localhost:8080/socket.io/?EIO=3&transport=websocket&sid=7MusFDtQFvZGBZloAAAD' failed: Invalid frame header
```

**Comment by PsychoLlama** [comment] 2016-11-29 03:06
Apparently gun sees the messages sent by socket.io ([`ws.js`](https://github.com/amark/gun/blob/master/lib/ws.js#L11)), but considers them invalid and doesn't attempt a reply ([`wsp.js`](https://github.com/amark/gun/blob/master/lib/wsp.js#L125)).

I don't see anywhere gun responds without running messages through the same validation, meaning the troublesome frame header might be coming from a lower level library.

With the code above, socket.io messaging works both ways alongside gun.

If it's just the warning, we're probably not going to pursue it for now. @Lightnet is socket.io messaging working on your setup?

**Comment by ctrlplusb** [comment] 2016-11-29 10:23
Thanks for taking the time to investigate this @PsychoLlama

**Comment by PsychoLlama** [comment] 2016-11-29 18:06
Sure thing @ctrlplusb! We wanna make sure gun plays nice with others :smile:

**Comment by amark** [comment] 2016-11-29 18:11
Thanks @PsychoLlama !

@ctrlplusb what are you working on? I'd love to hear about it. Looks like you got some nice/popular open source tools yourself!

**Comment by Lightnet** [comment] 2016-11-30 02:15
Well I am not sure it up to you. But it worth doing if someone wanted to used socket.io and gun at the same time. It has to be friendly but since I am not sure since it open idea. I not that good with coding that detail of work how header works.

**Comment by amark** [comment] 2016-11-30 02:25
@Lightnet good news, @PsychoLlama and I just made 0.5 a lot easier for adding transport plugins, here is an example of how easy it would be to receive messages:

```
ws.onmessage = function(msg){
	gun.on('in', JSON.parse(msg.data));
};
```

Also @Lightnet what are you working on?

**Comment by Lightnet** [comment] 2016-11-30 18:42
Working Babylonjs 3D web game sandbox dungeon/adventure theme prototype. Very early stuff. Just setting thing up later for editor web build.

**Comment by amark** [comment] 2016-12-01 00:12
`ws.onmessage` is just the Browser's API for listening to a WebSocket connection, kinda like `element.onclick = function(){}` is.

@Lightnet Nice! I would love to see that! Any early prototypes/demos? You'll definitely want to use the bleeding edge 0.5 branch as it has been engineered specifically for gaming and performance!

**Comment by Lightnet** [comment] 2016-12-01 04:40
Oh. I using chrome for testing and nodejs. Not sure how handle web browser to handle that. You can check out but it still very early develop. github > lightnet > bes-threejs. Current main is babylonjs_game. I have not work on gundb since it long ways to go. Need to build the editor for it.

**Comment by amark** [comment] 2017-02-20 23:57
Given Jesse's earlier analysis (here: https://github.com/amark/gun/issues/282#issuecomment-263463918 ) that was able to get the two working side by side, I'm gonna go ahead and close this issue.

Made any progress on your game, though?

**Closed by amark** 2017-02-20 23:57 UTC
