### ISSUE TITLE
How to subscribe to changes to changes in the whole graph

### ISSUE THREAD

**Issue by karlitos** [amark/gun#599] opened 2018-08-21 15:08 UTC
Hello,

first let me express my excitement about this project!

I wonder if there is a way, how to observe changes in the whole graph, instead of subscribing to changes on one particular node. I was not able to find an answer reading the Docs/Howtos

Lets say you build a real-time mind-mapping application, so basically a graph/tree structure.

1. If I add a new node - at some place - to the graph I want to update my UI
2. If I remove a node or a whole subtree ...

The 2. scenario is a a general concern: How can I delete multiple nodes together with all related edges ?

**Comment by Dletta** [comment] 2018-08-22 04:43
@karlitos 
Hi,

To answer the 1st, You could have an index root node that you subscribe to. New nodes would trigger the update function, where you will check what that node might be related to. 

To answer the 2nd, Delete in a decentralized system is hard. (Google tombstone problem) In Gun deletes are handled by putting null to an object, which cuts all edges from that item and it becomes unreachable. (Although you can still get the children nodes by their soul, or via the index node that you might add all children too, by default)

**Comment by karlitos** [comment] 2018-08-22 08:00
Hi and thanks for clarification.

Regarding 1) I would need to do tree/graph traversing manually (or is there such an functionality in Gun) for any new node added to the graph ? This  would be very hard to do in a case I manage multiple graphs/trees and would like to achieve real time updates. One possibility would be to manage unique Ids for every graph/tree - maybe like Tree-Id == root-Id. So how would I achieve the real-time updates among multiple clients with the knowledge, that a new node was added to the graph?

 Regarding 2) If I am understanding this correctly delete in gun would mean making a null reference to a node with possible sub-graph attached to it. So the whole sub-graph would still be present in the database and I would need to do a traversal  to clean it up.

**Comment by amark** [comment] 2018-08-22 08:09
@karlitos https://gun.eco/docs/API#open ?

**Comment by karlitos** [comment] 2018-08-22 09:36
@amark Thank you very much for the hint. I already stumbled upon the _open_ method in the docs. The issue with this is, that the callback gives you the _copy of your data_ and I fear this would be very inefficient for larger data set/huge graph/tree. I was thinking more about a some something like the Meteors [observeChanges](https://docs.meteor.com/api/collections.html#Mongo-Cursor-observeChanges) method.

**Comment by amark** [comment] 2018-08-22 11:55
@karlitos it reuses the same initial copy of the data on subsequent calls.

Loading the entire graph rather than each partial piece of a node is the thing that will be inefficient, so don't worry about API calls. 

Or if you do, please benchmark it first and show that there is a performance problem.

Internally only changes are sent already, but if you had an API that only gave you those changes you'd probably think it is terrible.

If you somehow want such an API yet don't want  fine grain control each piece on a node, then just fork Open... It is only like 50 lines, and change to `, true` like @Dletta suggested. Or Google for old Onward and Synchronous extension and see if they are what you want.

If there is a performance problem, please benchmark and make that the issue. No reason wasting your time :) avoiding an easier API that does what you want just for fear it might not be what you want. You could have built it already! :)

**Comment by amark** [comment] 2018-08-29 23:03
Could somebody please port this question to http://stackoverflow.com/questions/tagged/gun ?

Thank you!

Closing, as this is not a bug.

**Closed by amark** 2018-08-29 23:03 UTC

**Comment by Dletta** [comment] 2018-08-30 16:07
@amark posted to https://stackoverflow.com/questions/52101196/how-to-subscribe-to-changes-in-the-whole-gun-graph/52101302#52101302

Not sure I answered it thoroughly, I tried to generalize where possible to avoid readers to feel like they miss too much of the context to understand the answers. Let me know if I need to edit or add more information.

**Comment by amark** [comment] 2018-08-30 18:35
@Dletta my hero!
