### ISSUE TITLE
what problem is this library trying to solve?

### ISSUE THREAD

**Issue by davidm-public** [amark/gun#473] opened 2017-12-23 18:42 UTC
Struggling to understand the point of this library as it seems entirely unable to synchronize state between two process, below are screenshots from one of your "examples", but the same results occur in almost all the other examples, the library tries to 'sort of' synchronize state, but easily gets confused. 

So, what would be the application of a such a library?

<img width="638" alt="screen shot 2017-12-23 at 8 37 29 pm" src="https://user-images.githubusercontent.com/15961173/34321879-59509bc2-e821-11e7-8e5f-80e678450595.png">

Notice that messages are synchronized out of order: 

<img width="738" alt="screen shot 2017-12-23 at 8 37 20 pm" src="https://user-images.githubusercontent.com/15961173/34321880-598b64fa-e821-11e7-9489-d7e9b4f0a9c0.png">

**Comment by amark** [comment] 2017-12-23 18:59
@davidm-public IDK if I read this wrong or not, but this came off as **really rude**, FYI.

The todo-app isn't ordered, the chat app is ordered. If there is a bug in the sync, please report how to reproduce it.

Closing, as "what is the problem you are trying to solve" is not a bug. If you found a bug, please repost.

**Closed by amark** 2017-12-23 18:59 UTC

**Comment by davidm-public** [comment] 2018-03-02 05:54
@amark fair point, wasn't meant to be rude, just frustrated.
