### ISSUE TITLE
Setting multiple keys with one object 'leaks'

### ISSUE THREAD

**Issue by Stefdv** [amark/gun#476] opened 2017-12-29 16:49 UTC
```
gun.get('livingroom').put({
  light1:{state:'on'},
  light2:{state:'on'}
})
gun.get('livingroom').get('light2').put({state::'off'})
```
No problem, only light 2 goes 'off'
```
var newState = {state:'on'}
gun.get('livingroom').put({
  light1:newState,
  light2:newState
})
gun.get('livingroom').get('light2').put({state::'off'})
```
This is NOT good...now all lights goes 'off'

I have a jsbin ( http://jsbin.com/qigotuj/1/edit?js,console )

**Comment by Stefdv** [comment] 2017-12-29 17:02
As a workaround...
```
var newState = {state:'on'}
gun.get('livingroom').put({
  light1:Gun.obj.copy(newState),
  light2:Gun.obj.copy(newState)
})
```
This does solve the problem....but this is not very 'user friendly'

**Comment by dfreire** [comment] 2017-12-29 17:39
Right, using the same reference to `newState` is what's causing the problem.

**Comment by Stefdv** [comment] 2017-12-30 23:07
@dfreire Yes, the reference to the same object is a problem...Still i think that Gun should take care of that...;p

**Comment by eallik** [comment] 2018-03-11 15:29
I think this behavior is desirable, consider:

```
gun.get('companyRoles').put({
  general: samePerson,
  sales: samePerson
})
```

— you would want both `general` and `sales` pointing to the same object.

**Comment by amark** [comment] 2018-03-11 17:27
@Stefdv oh, see I didn't understand this issue now until @eallik has given an alternate example.

It **is true** what @eallik says, that the same object-reference in javascript is intended to convert to a same-graph node that multiple things can point to. So if this is what you were encountering, then it is intended behavior (and it would be impossible to "take care of" without also ruining graph features). Thank you @eallik for noticing this!

@Stefdv I thought you meant the object was "leaking through" into GUN's replies (as if, GUN wasn't properly "copying" the data, such that changes to the original object then also mutated internal GUN state. That would be wrong/bad).

I am going to close this, as what @eallik is true, this is intended. Please reopen, @Stefdv if you meant something else.

**Closed by amark** 2018-03-11 17:27 UTC
