### ISSUE TITLE
Include NTS by default in WSP

### ISSUE THREAD

**Issue by d3x0r** [amark/gun#221] opened 2016-09-30 23:18 UTC
Please to include Network Time Sync Protocol by default for Gun's WebSocket Protocol.

for the simplest collaborative apps, two people typing on a document, with a time skew even 12 seconds apart can cause syncronization issues... (bad wording)

---

d3x0r @d3x0r 15:58
@amark - so yes; the NTS routine is very tiny, and kinda critical to how gun functions; why isn't that just part of websock negotiation ?

Mark Nadal @amark 16:00
@d3x0r very bizarre actually. There is NO mention of this in the websocket spec (at least I didn't find anything). BUT when we ran a game we built with gun using NTS.... we discovered that Chrome was doing NTP for us (without NTS!!!!).
and it has baffled me ever since, because it SEEMS like it is simple enough that the websocket spec should do it / include it. It isn't suppose to, but in practice we saw it happening.
so we wound up not using NTS actually.
@d3x0r as far as your question though, quick clarification: Are you asking why NTS isn't included by default in the GUN websocket driver? Or why it isn't included in WebSocket standard itself?

d3x0r @d3x0r 16:02
gun more specifically than websocket...

Mark Nadal @amark 16:03
@d3x0r there is a strong argument that we should. So the initial excuse right now is: laziness / code bloat. However here other reasons to consider:

d3x0r @d3x0r 16:03
jitter

Mark Nadal @amark 16:05
You are building a game. A game is a CA system, not a CP or AP system. GUN's default is AP. Live action games do not need to be offline-first. In fact, you'll probably want to BOOT people from your game if their latency is high enough. As a result, NTS is only the most critical/necessary in apps like this - things like gaming or other CA systems. So is including NTS doing too much? Or not enough? IDK.

d3x0r @d3x0r 16:07
connection state is a non-sequitor. Of course if there's no connection there's no NTS

Mark Nadal @amark 16:07
Not all peers will want their clocks synced. This is unlikely to happen with any apps that us normal people are building. But what happens if you have code that is running on a satellite? The clock is INTENTIONALLY different. What about a Mars rover? They are running off of Mars UTC not Earth UTC. Trying to sync those could be bad. Instead, you want the offsets because the offsets are REAL results of physics.

d3x0r @d3x0r 16:07
it shouldn't sync the clock, only provide gun with a bias to adjust incoming times to localtime
or bias outgoing to remote time

Mark Nadal @amark 16:07
(funny ^ my above post is "2" but gitter is auto-correcting it to '1" lol)
@d3x0r ahh
that is a really really good argument!
This message was deleted

d3x0r @d3x0r 16:08
ya I wouldn't want to try and control a clock - that's an admin function I'm sure the browser doesn't let me access

Mark Nadal @amark 16:09
@d3x0r these are good points. And I was previously thinking of NTS in gun core, but having it in the websocket module is actually a very nice place to put it.
not a huge priority to me right now (since it is easy enough to add NTS) but

d3x0r @d3x0r 16:09
http://stackoverflow.com/questions/1976968/change-browser-time ... No.

Mark Nadal @amark 16:09
you have a good point
let's try to get this included at some point?

d3x0r @d3x0r 16:10
okay

Mark Nadal @amark 16:11
@d3x0r because you are right, it is safer to do it (than have people go "huh?") and the only times you WOULDN"T want to do it, are in edge-cases (with real physics and stuff) that those people coudl easily disable it. Right?
@d3x0r will you open up an issue called "Include NTS by default in WSP" for me?
so that way we'll get around to it?

**Comment by amark** [comment] 2017-02-20 23:20
Yeah, this is still a good point. Since the algorithm is pretty small and it prevents some major unexpected behavior. Gonna keep this issue open.

**Comment by d3x0r** [comment] 2017-04-02 08:05
require( "gun/lib/nts.js" ) ?

How does one use such a thing?   Does it need a wiki page?

**Comment by amark** [comment] 2017-04-02 09:42
Been off having fun with my family this weekend. NTS is now included by default. (see lib/server.js) all you need to do is include it on client with a gun server as /gun/lib/nts.js script tag.

**Comment by amark** [comment] 2017-04-05 19:52
It is now included by default in the server! :D Closing.

**Comment by d3x0r** [comment] 2017-04-05 22:19
Didn't really answer how to use it.  How does it know which connection has which time skew if I don't interact with it from my connections

**Comment by amark** [comment] 2017-07-07 07:32
Here is how:

By default, server-side, when you include `require('gun')` it automatically gets added to the server.

In the browser you do:

```
<script src="/gun.js"></script>
<script src="/gun/nts.js"></script>
```

(note: the default server auto CDN-ifies the gun folders on a /gun route!).

Additionally, see https://github.com/amark/gun/blob/master/examples/game/nts.html as an example.

Note: NTS is currently not working in `v0.8.0` but will be working again (upgraded) in `v0.8.1` which I'll be releasing soon.

Gonna close though.

**Closed by amark** 2017-07-07 07:32 UTC

**Comment by d3x0r** [comment] 2017-07-07 08:31
Still no documentation on how I apply it per connection; 'How does it know which connection has which time skew'

**Comment by amark** [comment] 2017-07-07 10:50
Right now the servers don't change, just to keep things simpler. This module isn't supposed to be "used", as in it has no API, it just silently runs in the background. Does that make sense? 

It is only less than 50 lines of code: https://github.com/amark/gun/blob/master/nts.js, if you have any ideas on how to extend it further, that would be cool. But there isn't an API, so the only way to use it is just to include it. 

Is there some game or app that you were planning on using it for, that it doesn't work with? Maybe I had a different assumption on what it is suppose to do, what were you needing / wanting it to do?
