### ISSUE TITLE
Is GUN Suitable for Sharing Binary Data?

### ISSUE THREAD

**Issue by zicklag** [amark/gun#1128] opened 2021-09-04 23:44 UTC
Hi there! First off, I'm using the issue tracker to ask a question. Not sure if that is preferable to this community or not, and just let me know if you would prefer that I didnt. I know that getting on chat is your usual channel for answering question, but I won't usually be able to get on chat so I figured I'd try here.

My question is whether or not GUN has any provision for sharing binary data. As far as I've been able to find, it seems that only JSON key-values can be replicated, which limits binary data sharing to be base64 encoded strings, which can waste about 30% of the storage space if I remember correctly. Is there any ways around this or ways to distribute binary data?

I'd love to be able to just use GUN to store all my data, instead of needing to supplement with IPFS, especially with IPFS not working natively on AXE ( which I would really love to be able to use to be Internet free some day ).

If this isn't something that GUN does today, are there any plans for it in the future, or are you open to ideas for supporting it?

---

Finally, **I am like mind blown by the capability of GUN right now**. I keep saying that it's the best idea/project that I've seen since Rust ( which is saying a lot for me, I absolutely love Rust and use it for almost everything ). Keep up the good work! If this keeps working in my tests I will very likely be building a lot with GUN.

**Comment by amark** [comment] 2021-09-20 05:12
@zicklag yeah issues are meant for bugs, not Qs. Chat is meant for help. StackOverflow for bugs.

I've hated JSON since the beginning, its terrible for graphs (no circular references), but its the standard format everyone uses so... sigh. People are doing Base64 in GUN, and its about +15% overhead, which sucks but is pretty good given binary/buffer support (shockingly???) is different between Browser, NodeJS, etc. and different platforms.

Binary data has been supported in some adapters (... I think by the Meething team), so yes. But the problem is that as soon as you have a peer that does not support binary, it has to get re-encoded anyways. This really sucks. So the answer is yes its possible, but its not universally compatible (how on earth is binary not universally compatible? Absurd). If people willing to contribute web + nodejs + android/ios binary networking & storage adapters, that'd be epic - but yeouch, that's a lot of work so I'm gonna leave it to whoever needs that 15% overhead saving > than universal compatibility.

Thanks! I hope this didn't burst your bubble too much. I sent you links to the beginning Rust port. Let me know if you can do a call to continue with me + pancy + others? Cheers. Closing.

**Closed by amark** 2021-09-20 05:12 UTC
