### ISSUE TITLE
Strategies at searching data

### ISSUE THREAD

**Issue by ctrlplusb** [amark/gun#336] opened 2017-03-10 07:46 UTC
Are there plans to make search a first class citizen or should we be looking to sync data into a 3rd party service such as Elastic?

Interested to hear the thoughts/experiences of anyone whom has had a proper go at this. 😀

**Comment by amark** [comment] 2017-03-10 09:45
We intend on building our own FTS index/search extension, probably based on tagging in general.

However it is really low on the list (I doubt it will happen this year). So if it is easier than that to hook things up to Elastic I think that would serve a useful purpose for a long while. A shame though, since graphs are so good at this. :(

**Comment by ctrlplusb** [comment] 2017-03-10 12:33
I appreciate the honest answer!

**Comment by amark** [comment] 2017-03-17 11:26
@ctrlplusb since you are such an outstanding member of the community :D let me know if you want to sit down on a weekend and see if we can hack out a prototype of this or not. Or if you decided to just go with Elastic for now. Let me know, but gonna close this for now as "not a bug" even though this is definitely a good idea ( or re: https://github.com/gundb/feature-requests/issues ).

**Closed by amark** 2017-03-17 11:26 UTC

**Comment by ctrlplusb** [comment] 2017-03-17 11:29
@amark that would be such an amazing opportunity for myself - to be able to work with you for a bit.  😊

I would love love love to do this, but it will have to be after a couple of months.  I have a lot going on right now as I am sure you do too.  But I will ping you a PM and we can see if something works for us both.  It's so tricky juggling work and family - as you know. 😊

**Comment by amark** [comment] 2017-03-17 11:37
Awesome, lets do it! Boohoo to a couple of months ;) but yeah I know how it goes. Definitely feel free to ping me whenever though. Keep up the hard work! :D

**Comment by amark** [comment] 2017-03-17 11:37
@ctrlplusb  ^
