### ISSUE TITLE
How does it compare to `level-graph`?

### ISSUE THREAD

**Issue by serapath** [amark/gun#93] opened 2015-08-31 13:00 UTC
https://github.com/mcollina/levelgraph

**Comment by RangerMauve** [comment] 2015-08-31 14:49
Levelgraph doesn't have the DB synchronization, though you could acheive that by using something like [level-replicate](https://github.com/dominictarr/level-replicate) As well the actual graph is a lot more simple and more graph-like IMO since you have clearly defined nodes and relationships. The way relationships between nodes in GUN work is more like a pointer where an arbitrary property of a node contains the unique identifier of the node it's linking to. It seems that in GUN the relationships are directed, and there doesn't seem to be a way to see what nodes are pointing at node `A` if all you have is the id of node `A`. However it's very flexible for how you want to actually structure your links between nodes because of this.

**Comment by amark** [comment] 2015-08-31 20:18
Wow, @RangerMauve answered that better that I could have. Thank you. @serapath any other questions? Let us know. Or if you are happy by closing the issue.

**Comment by serapath** [comment] 2015-10-24 00:25
What i like about `levelgraph` is that it builds on top of the level ecosystem and i can combine it with a lot of other features. That's a big plus.
I wrote https://www.npmjs.com/package/level-tracker for example to be able to listen to changes to the database.

**Comment by amark** [comment] 2015-10-24 00:43
@serapath that's a really nice feature, it also matches similar to the requirements for the `.all` wire command we're adding to gun. I'll have to take a poke around on how you did it. We're also making requests for a module to use Level as the storage engine.

Another item on our lengthy to do list is adding a module that handles creating edge nodes automatically. But it sounds like the level ecosystem is already pretty well developed. GUN's specialty is sync focused.

**Comment by serapath** [comment] 2015-10-24 00:56
I feel, whenever I start to use a certain type of database extensively, i slowly forget how I used databases before - it's been a long time since the last time i actually used a relational database even though back in the days i sometimes wrote some more involved queries.

I really enjoy that with learning the level ecosystem, i slowly learn more modules to customize my database the way i need and it lead to me being reluctant to loose all that knowledge by buying again into some kind of new database with all kinds of special features - so i rather hope that people write something on top of leveldb, so that i can re-use other features i've discovered :-)

**Comment by amark** [comment] 2015-10-24 01:05
Definitely, the UNIX/NodeJS philosophy of doing very little and leaving everything else up to modules is a huge win for everyone. As you say it, customizing your database to your needs rather than buying into the handwaving magic of big vendors.

We're definitely going to make use of Level as a storage engine, but I'm not sure how compatible everything else will be beyond that because Level was designed with disk level storage performance as its goal - gun's goal is concurrency, and may not even use the local disk (in favor of in memory peers and S3 and other cloud storage). So a lot of the level ecosystem might be lost on gun. Hopefully not, but at least we'll be able to use it as a good disk layer, I'd hate to write my own storage engine - reinventing the wheel isn't necessary there.

**Comment by serapath** [comment] 2015-10-24 01:08
I'm using `level-js` for use in the browser on top of the otherwise horrible `indexDB`
I'm using `memdown` to not use any persistance.

Sometimes I'm using `level-browserify` so it works in the browser and node depending on where I run my program.

**Comment by amark** [comment] 2015-11-17 19:14
@serapath great news! @PsychoLlama wrote a https://github.com/PsychoLlama/gun-level module! So we now actually have a legit persistence layer!! Woohoo. I hope this shows you that we are trying to play nicely with other ecosystems, and NOT reinventing wheels.

Also, would you be willing to add whatever project you are working on and might want to use gun to https://github.com/amark/gun/wiki/projects ?

**Comment by serapath** [comment] 2015-11-17 19:51
nice :-) sure. don't have a project yet, but i'll keep it in mind

**Comment by metasean** [comment] 2015-11-17 23:07
At this time, we recommend the use of https://github.com/PsychoLlama/gun-level

@serapath  - looking forward to seeing what you build! :smile:

**Closed by metasean** 2015-11-17 23:07 UTC
