### ISSUE TITLE
Update docker image for 0.9.99+

### ISSUE THREAD

**Issue by jadbox** [amark/gun#561] opened 2018-06-10 04:11 UTC
It seems the latest image is over 4 months old:

https://hub.docker.com/r/gundb/gun/tags/

**Comment by amark** [comment] 2018-06-12 22:31
@jadbox thanks, you any good at Docker stuff? I have 0 knowledge of it, would love a PR to fix it!

**Comment by jadbox** [comment] 2018-06-13 04:06
I would, but it's not really a code chance.
```
docker build -t gundb/gun:master
docker push gundb/gun:master
```
The current image is hosted at: https://hub.docker.com/r/gundb/gun/
It looks like the published image came from this person/fork: https://github.com/hillct/gun

@hillct Maybe you could update your repo and republish?

**Comment by jadbox** [comment] 2018-06-13 20:16
For what's it worth, I've published 0.9.99 under my dockerhub account, but I recommend taking control of the official gundb Docker account for future updates.
https://hub.docker.com/r/jadbox/gundb/

**Comment by lmangani** [comment] 2018-06-29 19:03
@amark I can happily take care of this and its automation if you want

**Comment by amark** [comment] 2018-06-29 23:03
Thanks @jadbox & @lmangani !

**Comment by hillct** [comment] 2018-06-30 01:38
I’ll update it this weekend.

**Comment by lmangani** [comment] 2018-06-30 14:52
If you don't mind creating a `gun-docker` repo in your organization and give us contributor access, we can schedule proper automated builds with codefresh or travis w/o 3rd party repositories. I have everything ready to go.

**Comment by hillct** [comment] 2018-06-30 16:11
It appears the github smtp gateway is a bit sluggish today so here's the content of my earlier emailed reply:

Lorenzo,
   I gather you weren't privy to the machinations that led up to it being implemented this way. Mark already has contributor access to the gundb org on Docker Hub. The issue with automating it out of the gundb org on Github seems to relate errors on the part of Docker, as to improperly scoping their oauth requests. There's a thread about this a year or so ago. Perhaps they've addressed this failing since then. Regardless, given the development workflow for gun as it stands now, the Docker autobuild (already in place) simply needs to be pulled from the amark/gun repo rather than my own. The only reason that was not done previously was Mark was not comfortable with doing so at that time.
   In your comments you suggest "we can schedule proper automated builds with codefresh or travis w/o 3rd party repositories" which betray a fundamental misunderstanding of the way docker auto-builds operate. The builds are performed upon any new code checking (provided that checkin passes travis-CI (in this case) or whatever test set/framework you have in palace. This is the point of continuous integration. There's no need to 'schedule' anything. That's what the 'latest' tagged build is. For clarity, we also tag each 'release' so users have a convenient regression testing process, short of having to hunt down the relevent checkin, and do a manual build.

Mark,
   If you're ready to do so now, I'm happy to walk you through that setup process (maybe 5 minutes or less worth of work). At this point I guess Lorenzo is also willing to help you with that, but as for privileges, Mark, you already have all the required privileges.

**Comment by lmangani** [comment] 2018-06-30 18:36
@hillct I've been involved with the project long and with Docker even longer, no need to give the elementary explanation of what an image is, but thanks nevertheless - I build dozens of images for dozens of projects I run and manage - not sure what your comment is about and I would say it betrays a fundamental misunderstanding of my proposal and I fail to see the usefulness of it. Perhaps a background check next time to avoid wasting time and bits. This being said, my point was to attach any such procedure to the original repository rather than use mine, yours or anyone else's fork to avoid this inevitably going un-maintained and obsolete - particularly now at the speed of recent releases.

**Comment by hillct** [comment] 2018-06-30 20:45
@lmangani, You've again missed the point, although you are correct in that, you should have made an effort to get more background on this before reproducing effort, as you said you've done. Of course, if you have any contributions to improve the Dockerfile or other aspects of the build, please feel free to submit a PR. Beyond that, Mark has the needed access, so when he's ready to start building from his repo, then we'll move the more direct build process, which will of course yield something closer to continuous integration for the Docker images. Until then, I've provided a workflow that will allow you to build a docker image from any checkin, on any branch you see fit (see documentation). If you're having difficulty with that documentation - again - please feel free to submit a PR with your suggested improvements.

**Comment by lmangani** [comment] 2018-06-30 21:12
@hillct hahaha sure thing!

**Comment by hillct** [comment] 2018-07-08 23:59
The docker build has been updated. Closing,

**Closed by hillct** 2018-07-08 23:59 UTC
