### ISSUE TITLE
legacy system

### ISSUE THREAD

**Issue by wanghaisheng** [amark/gun#471] opened 2017-12-21 12:45 UTC
there are bunch of legacy system where they use ER databases such as oralce sqlserver  mysql and system run agaisnt them still works fine and we like to keep them as well . is there any way we can stream data existing in  and out the old ER databses into gundb and build new app against gundb

**Comment by amark** [comment] 2017-12-21 23:02
Yes, a customer of ours is doing that right now (they use gun just as an "in-memory" cache to sync clients).

Take note though, that if gun is not the gatekeeper (it handles conflict resolution, concurrency, eventual consistency, etc.), you may have to separately handle consistency issues.

Obviously we're not creating/building/supporting any legacy-proprietary-system as Open Source itself. If you guys are interested in us building an integration though (or helping you), we can do that on a consulting basis - check out the Elite (or above) plans on https://www.patreon.com/gunDB .

:) Let me know, happy to help out! Gonna close this though, as it is not a bug, but thank you for asking about it.

**Closed by amark** 2017-12-21 23:03 UTC
