### ISSUE TITLE
nodes get created in the wrong place along the path

### ISSUE THREAD

**Issue by d3x0r** [amark/gun#203] opened 2016-07-09 04:39 UTC
```
var Gun = require( 'gun' );

var gun = Gun();

var gdb = gun.get( 'com.example.www/database' ).path("dataset");
var level2 = gdb.path( "Name1" );
level2.put( { name : "Name1" } );
var level3 = level2.path( "data" )
level3.path( "table" ).path( "row1" ).put( { data: "data goes here" } );

// gdb.map( function(val,field){ console.log( "Debug map : ", field, "=", val ) } );
 gdb.path( "row1" ).val( (val,field)=>{ console.log( "this doesn't exist here: ", field, "=", val ) } );
```

there should not be a 'row1' value in dataset.

(I'm not sure how the map fires in this simple set, in the more complex case, it was firing when 'row1' is created with row1 as a field and value.... that means it's created in the 'dataset' field which is mapped.  It's not like I'm doing recursive mapping...  Which is what led me to questions like 'how do I know WHERE this is'... which yes, I would need parent identifiers or self-circular references otherwise... but really I shouldn't be getting those events, but a map in the correct path later might and would of course know the context )

It's only on the initial create... after adding row1, adding row2 goes into the correct location ( for most of the paths created afterward, the first set actually gets row2 created one level above; but that involves servers and will probably get fixed as a result of this fix)

**Comment by amark** [comment] 2016-07-11 07:33
@d3x0r thanks for reporting this!

I wasn't able to reproduce it on my end: http://jsbin.com/vojasotuge/edit?js,console . However I have seen this problem before and we have some tests for it - but that doesn't mean we're covering every edge case.

What I would like to get from you is: 1) What environment are you running this in? 2) What type of peers are connected?

Then I'll do a follow up test to replicate the problem. Thanks for reporting this!

**Comment by amark** [comment] 2016-07-11 21:48
@d3x0r confirmed this doesn't work in NodeJS.

Boo :( maybe it is an artifact of one of the storage driver. I'll check into this and let you know...

**Comment by amark** [comment] 2016-07-11 23:40
fixed/masked with https://github.com/amark/gun/pull/204 .

Now published, a `npm install gun` should pull in `v0.3.98`!

Closing. :)

**Comment by d3x0r** [comment] 2016-08-05 17:09
This didn't work; it caused a reversion in the other fix for ... something else.

**Comment by amark** [comment] 2016-08-05 18:45
Maybe we need to go back over this and #207 ?

**Comment by amark** [comment] 2017-02-20 23:11
Okay, this looks fixed now with all the major improvements in the new version.

You said that row1 should NOT exist, and it looks like name1 SHOULD exist, which is exactly what shows up now: http://jsbin.com/vojasotuge/edit?js,console .

So I'm gonna close, again . :) Please reopen if not. I hope you are doing well @d3x0r - you must be building something really cool, as you seem to be quiet lately.

**Closed by amark** 2017-02-20 23:11 UTC
