### ISSUE TITLE
Clean null objects?

### ISSUE THREAD

**Issue by newturok** [amark/gun#485] opened 2018-01-18 00:34 UTC
With put(null)
![image](https://user-images.githubusercontent.com/5757827/35074715-e09f99ae-fbf7-11e7-95c9-4905e87402cc.png)
i get big count of nulls if get('videos')
![image](https://user-images.githubusercontent.com/5757827/35074703-d084b608-fbf7-11e7-8d5b-b596b1eb432d.png)
Is there any way to clean it up?

**Comment by amark** [comment] 2018-02-03 19:44
@newturok my 2nd son was born around when you posted this, which explains the delay!

Currently the `null`s are needed for correct P2P/distributed deleting (called a tombstone, same method Cassandra uses).

There is a way to clean them up, but I'd need to hear/learn more about the application your building, so that way any suggestion I make doesn't have odd side-effects. Even then, there isn't a super good implementation for it yet. So we'd need to chat.

Up for expanding on details?

**Comment by amark** [comment] 2018-02-23 17:23
The `null` are correct behavior (as indicated in previous post), so this is not a bug and therefore will be closing this issue. Obviously, at some point, a way to clean them up would be nice, but that probably won't be handled by core but an adapter or extension that somebody can build.

**Closed by amark** 2018-02-23 17:23 UTC
